vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /image/properties
            upload_destination: 'kernel.project_dir%/public/images/properties'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

